//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibo.Examen.DAL.Model2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SiboSupermarket1Entities1 : DbContext
    {
        public SiboSupermarket1Entities1()
            : base("name=SiboSupermarket1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adviser> Adviser { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetail { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    
        public virtual int spSaveInvoice2(Nullable<int> clientID, Nullable<int> adviserID, Nullable<System.DateTime> theDate)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(int));
    
            var adviserIDParameter = adviserID.HasValue ?
                new ObjectParameter("AdviserID", adviserID) :
                new ObjectParameter("AdviserID", typeof(int));
    
            var theDateParameter = theDate.HasValue ?
                new ObjectParameter("TheDate", theDate) :
                new ObjectParameter("TheDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSaveInvoice2", clientIDParameter, adviserIDParameter, theDateParameter);
        }
    }
}
